<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Event\Event;

/**
 * Miscellaneous Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Locations
 * @property \Cake\ORM\Association\BelongsTo $Users
 *
 * @method \App\Model\Entity\Miscellaneous get($primaryKey, $options = [])
 * @method \App\Model\Entity\Miscellaneous newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Miscellaneous[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Miscellaneous|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Miscellaneous patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Miscellaneous[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Miscellaneous findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class MiscellaneousTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('miscellaneous');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Locations', [
            'foreignKey' => 'location_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('description', 'create')
            ->notEmpty('description');

        $validator
            ->numeric('amount')
            ->requirePresence('amount', 'create')
            ->notEmpty('amount');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['location_id'], 'Locations'));
        $rules->add($rules->existsIn(['user_id'], 'Users'));

        return $rules;
    }

    /**
     * @param EntityInterface $entity
     * @param ArrayObject $options
     * @return bool
     */
    protected function _onSaveSuccess($entity, $options)
    {

        $event = new Event('Controller.expenses.log',['MISCELLANEOUS'],['subject'=>'MISCELLANEOUS','amount'=>$entity->amount,'expenditure_statement'=>$entity->description.' with Log no: <a href="miscellaneous/view/'.$entity->id.'">'.$entity->id.'</a>']);
        $this->eventManager()->dispatch($event);

        return parent::_onSaveSuccess($entity, $options); // TODO: Change the autogenerated stub
    }
}
